output_name = "cilok"
pretrained_model_name_or_path = "C:\\Projects\\gendojo\\models\\anima\\dit\\anima_preview.safetensors"
output_dir = "C:\\Projects\\gendojo\\outputs/cilok"
network_dim = 32
network_alpha = 32
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
lr_scheduler = "cosine_with_restarts"
max_train_epochs = 10
save_every_n_epochs = 1
mixed_precision = "bf16"
save_precision = "bf16"
gradient_checkpointing = true
cache_latents = true
qwen3 = "C:\\Projects\\gendojo\\models\\anima\\text_encoder\\qwen3_06b\\model.safetensors"
vae = "C:\\Projects\\gendojo\\models\\anima\\vae\\qwen_image_vae.safetensors"
timestep_sampling = "sigmoid"
dataset_config = "C:\\Projects\\gendojo\\temp\\jobs\\68e8d1bd-4d95-4f58-9d07-a9bf9f5b6bd1\\dataset.toml"
network_module = "networks.lora_anima"
