export type {
  SystemSnapshotDto as SystemSnapshot,
  MemorySnapshotDto as MemorySnapshot,
  GpuSnapshotDto as GpuSnapshot,
  DisksSnapshotDto as DisksSnapshot,
  CpuInfoDto as CpuInfo,
  DiskInfoDto as DiskInfo,
  GpuInfoDto as GpuInfo,
  GpuUtilizationDto as GpuUtilization,
  PowerInfoDto as PowerInfo,
  VramInfoDto as VramInfo,
  MemoryInfoDto as MemoryInfo
} from '@api/types.gen'