/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets/index'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs/new'
import { Route as AuthenticatedDatasetsUploadRouteImport } from './routes/_authenticated/datasets/upload'
import { Route as AuthenticatedDatasetsViewDatasetNameRouteImport } from './routes/_authenticated/datasets/view/$datasetName'
import { Route as AuthenticatedDatasetsEditDatasetNameRouteImport } from './routes/_authenticated/datasets/edit/$datasetName'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsUploadRoute =
  AuthenticatedDatasetsUploadRouteImport.update({
    id: '/datasets/upload',
    path: '/datasets/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatasetsViewDatasetNameRoute =
  AuthenticatedDatasetsViewDatasetNameRouteImport.update({
    id: '/datasets/view/$datasetName',
    path: '/datasets/view/$datasetName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatasetsEditDatasetNameRoute =
  AuthenticatedDatasetsEditDatasetNameRouteImport.update({
    id: '/datasets/edit/$datasetName',
    path: '/datasets/edit/$datasetName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/datasets/upload': typeof AuthenticatedDatasetsUploadRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/datasets/edit/$datasetName': typeof AuthenticatedDatasetsEditDatasetNameRoute
  '/datasets/view/$datasetName': typeof AuthenticatedDatasetsViewDatasetNameRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof AuthLoginRoute
  '/datasets/upload': typeof AuthenticatedDatasetsUploadRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/datasets/edit/$datasetName': typeof AuthenticatedDatasetsEditDatasetNameRoute
  '/datasets/view/$datasetName': typeof AuthenticatedDatasetsViewDatasetNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/datasets/upload': typeof AuthenticatedDatasetsUploadRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/datasets/edit/$datasetName': typeof AuthenticatedDatasetsEditDatasetNameRoute
  '/_authenticated/datasets/view/$datasetName': typeof AuthenticatedDatasetsViewDatasetNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/datasets/upload'
    | '/jobs/new'
    | '/datasets/'
    | '/jobs/'
    | '/models/'
    | '/settings/'
    | '/datasets/edit/$datasetName'
    | '/datasets/view/$datasetName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/datasets/upload'
    | '/jobs/new'
    | '/datasets'
    | '/jobs'
    | '/models'
    | '/settings'
    | '/datasets/edit/$datasetName'
    | '/datasets/view/$datasetName'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/'
    | '/_authenticated/datasets/upload'
    | '/_authenticated/jobs/new'
    | '/_authenticated/datasets/'
    | '/_authenticated/jobs/'
    | '/_authenticated/models/'
    | '/_authenticated/settings/'
    | '/_authenticated/datasets/edit/$datasetName'
    | '/_authenticated/datasets/view/$datasetName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/upload': {
      id: '/_authenticated/datasets/upload'
      path: '/datasets/upload'
      fullPath: '/datasets/upload'
      preLoaderRoute: typeof AuthenticatedDatasetsUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/view/$datasetName': {
      id: '/_authenticated/datasets/view/$datasetName'
      path: '/datasets/view/$datasetName'
      fullPath: '/datasets/view/$datasetName'
      preLoaderRoute: typeof AuthenticatedDatasetsViewDatasetNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/edit/$datasetName': {
      id: '/_authenticated/datasets/edit/$datasetName'
      path: '/datasets/edit/$datasetName'
      fullPath: '/datasets/edit/$datasetName'
      preLoaderRoute: typeof AuthenticatedDatasetsEditDatasetNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDatasetsUploadRoute: typeof AuthenticatedDatasetsUploadRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedDatasetsEditDatasetNameRoute: typeof AuthenticatedDatasetsEditDatasetNameRoute
  AuthenticatedDatasetsViewDatasetNameRoute: typeof AuthenticatedDatasetsViewDatasetNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDatasetsUploadRoute: AuthenticatedDatasetsUploadRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedDatasetsEditDatasetNameRoute:
    AuthenticatedDatasetsEditDatasetNameRoute,
  AuthenticatedDatasetsViewDatasetNameRoute:
    AuthenticatedDatasetsViewDatasetNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
