/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  http: {
    api: {
      Mfa: () => import('#controllers/HTTP/API/mfa_controller'),
      Models: () => import('#controllers/HTTP/API/models_controller'),
      Settings: () => import('#controllers/HTTP/API/settings_controller'),
      System: () => import('#controllers/HTTP/API/system_controller'),
    },
    web: {
      Models: () => import('#controllers/HTTP/web/models_controller'),
      Session: () => import('#controllers/HTTP/web/session_controller'),
      Settings: () => import('#controllers/HTTP/web/settings_controller'),
    },
  },
}
