/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type SettingTransformer from '#transformers/setting_transformer'
import type TokenTransformer from '#transformers/token_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type WeightsFileTransformer from '#transformers/weights_file_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Setting = InferData<SettingTransformer>
  export namespace Setting {
    export type Variants = InferVariants<SettingTransformer>
  }
  export type Token = InferData<TokenTransformer>
  export namespace Token {
    export type Variants = InferVariants<TokenTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type WeightsFile = InferData<WeightsFileTransformer>
  export namespace WeightsFile {
    export type Variants = InferVariants<WeightsFileTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
