/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class SettingSchema extends BaseModel {
  static $columns = ['accelerateConfigPath', 'cpuThreadsPerProcess', 'datasetsPath', 'id', 'logBufferSize', 'logsPath', 'maxConcurrentJobs', 'modelsPath', 'outputsPath', 'sdScriptsPath', 'tempPath', 'theme', 'updatedAt'] as const
  $columns = SettingSchema.$columns
  @column()
  declare accelerateConfigPath: string | null
  @column()
  declare cpuThreadsPerProcess: number | null
  @column()
  declare datasetsPath: string | null
  @column({ isPrimary: true })
  declare id: string | null
  @column()
  declare logBufferSize: number | null
  @column()
  declare logsPath: string | null
  @column()
  declare maxConcurrentJobs: number | null
  @column()
  declare modelsPath: string | null
  @column()
  declare outputsPath: string | null
  @column()
  declare sdScriptsPath: string | null
  @column()
  declare tempPath: string | null
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TokenSchema extends BaseModel {
  static $columns = ['createdAt', 'hint', 'id', 'token', 'type', 'updatedAt'] as const
  $columns = TokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare hint: string
  @column({ isPrimary: true })
  declare id: string | null
  @column()
  declare token: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isMfaEnabled', 'mfaSecret', 'password', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isMfaEnabled: boolean
  @column()
  declare mfaSecret: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class WeightsFileSchema extends BaseModel {
  static $columns = ['architecture', 'category', 'createdAt', 'expectedSha256', 'filename', 'id', 'name', 'provider', 'providerId', 'relativePath', 'role', 'sizeBytes', 'status', 'updatedAt'] as const
  $columns = WeightsFileSchema.$columns
  @column()
  declare architecture: string
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare expectedSha256: string | null
  @column()
  declare filename: string
  @column({ isPrimary: true })
  declare id: string | null
  @column()
  declare name: string
  @column()
  declare provider: string
  @column()
  declare providerId: string | null
  @column()
  declare relativePath: string
  @column()
  declare role: string
  @column()
  declare sizeBytes: bigint | number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
